import type { NextPage } from "next";
import Head from "next/head";

import { Center } from "@chakra-ui/react";
import SelectParamsForm from "../SelectParamsForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Learn Foreign Numbers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SelectParamsForm />
    </>
  );
};

export default Home;
